export const CREATE_ROOM = "CREATE_ROOM";
export const CREATE_ROOM_SUCCESS = "CREATE_ROOM_SUCCESS";
export const LOAD_ROOM = "LOAD_ROOM";
export const LOAD_LOAD_SUCCESS = "LOAD_ROOM_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
